//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVSbase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PVSEntities : DbContext
    {
        public PVSEntities()
            : base("name=PVSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Виды_Вторичного_Сырья> Виды_Вторичного_Сырья { get; set; }
        public DbSet<Должности> Должности { get; set; }
        public DbSet<Послужной_Список> Послужной_Список { get; set; }
        public DbSet<Принятое_Сырье> Принятое_Сырье { get; set; }
        public DbSet<Складские_Помещения> Складские_Помещения { get; set; }
        public DbSet<Сотрудники> Сотрудники { get; set; }
        public DbSet<Типы_Складских_Помещений> Типы_Складских_Помещений { get; set; }
    }
}
