//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVSbase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Виды_Вторичного_Сырья
    {
        public Виды_Вторичного_Сырья()
        {
            this.Принятое_Сырье = new HashSet<Принятое_Сырье>();
            this.Типы_Складских_Помещений = new HashSet<Типы_Складских_Помещений>();
        }
    
        public int IDВВС { get; set; }
        public string Условия_Хранения { get; set; }
        public string Условие_Приёма_тара__упаковка_ { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Цена_За_Килограмм { get; set; }
        public string Описание { get; set; }
    
        public virtual ICollection<Принятое_Сырье> Принятое_Сырье { get; set; }
        public virtual ICollection<Типы_Складских_Помещений> Типы_Складских_Помещений { get; set; }
    }
}
