//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVSbase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Должности
    {
        public Должности()
        {
            this.Послужной_Список = new HashSet<Послужной_Список>();
        }
    
        public int IDДолжности { get; set; }
        public string НаименованиеДолжности { get; set; }
        public Nullable<int> Оклад { get; set; }
        public string Обязанности { get; set; }
        public string Требования { get; set; }
    
        public virtual ICollection<Послужной_Список> Послужной_Список { get; set; }
    }
}
