//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVSbase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Послужной_Список
    {
        public int IDПослужной_Список { get; set; }
        public Nullable<int> IDСотрудника { get; set; }
        public Nullable<int> IDДолжности { get; set; }
        public string НаименованиеСписка { get; set; }
        public Nullable<System.DateTime> Дата_Принятия { get; set; }
        public Nullable<System.DateTime> Дата_Выхода { get; set; }
        public string Краткая_Характеристика { get; set; }
    
        public virtual Должности Должности { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
