//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVSbase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Принятое_Сырье
    {
        public int IDПС { get; set; }
        public Nullable<int> IDВВС { get; set; }
        public Nullable<int> Количество_в_КГ { get; set; }
        public Nullable<int> Цена { get; set; }
        public Nullable<System.DateTime> Дата_и_Время_Приема { get; set; }
        public string Помещение_Хранения { get; set; }
        public Nullable<int> СотрудникПриема { get; set; }
    
        public virtual Виды_Вторичного_Сырья Виды_Вторичного_Сырья { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
