//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVSbase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Складские_Помещения
    {
        public int IDСП { get; set; }
        public string НаименованиеПомещения { get; set; }
        public Nullable<int> Инвентарный_Номер { get; set; }
        public Nullable<int> Площадь { get; set; }
        public Nullable<int> Вместимость_В_Тоннах { get; set; }
        public Nullable<int> Процент_Заполнения { get; set; }
        public Nullable<int> Ответственный { get; set; }
        public Nullable<int> Степень_Изношенности_Помещения { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Дата_Последней_Проверки_Пожарной_Инспекции { get; set; }
        public string Дополнительный_Отметки { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
