//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVSbase
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Типы_Складских_Помещений
    {
        public int IDТСП { get; set; }
        public string Наименование_Типа_Помещения { get; set; }
        public Nullable<int> IDВВС { get; set; }
        public Nullable<int> Средняя_Температура { get; set; }
        public Nullable<int> Влажность { get; set; }
        public string Требования_Пожарной_Безопасности { get; set; }
        public string Наличие_Спецоборудования { get; set; }
    
        public virtual Виды_Вторичного_Сырья Виды_Вторичного_Сырья { get; set; }
    }
}
